// <auto-generated>
//     This code was generated by a designer.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace JointTorqueVisualizer
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.panelAnimation = new System.Windows.Forms.Panel();
            this.panelTorqueGraph = new System.Windows.Forms.Panel();
            this.numericUpDownJointCount = new System.Windows.Forms.NumericUpDown();
            this.labelJointCount = new System.Windows.Forms.Label();
            this.flowLayoutThetaInputs = new System.Windows.Forms.FlowLayoutPanel();
            this.buttonPlay = new System.Windows.Forms.Button();
            this.buttonPause = new System.Windows.Forms.Button();
            this.buttonStop = new System.Windows.Forms.Button();
            this.labelTorqueTheta = new System.Windows.Forms.Label();
            this.numericUpDownPayload = new System.Windows.Forms.NumericUpDown();
            this.labelPayload = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownJointCount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownPayload)).BeginInit();
            this.SuspendLayout();
            // 
            // panelAnimation
            // 
            this.panelAnimation.BackColor = System.Drawing.Color.White;
            this.panelAnimation.Location = new System.Drawing.Point(16, 15);
            this.panelAnimation.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.panelAnimation.Name = "panelAnimation";
            this.panelAnimation.Size = new System.Drawing.Size(1038, 1027);
            this.panelAnimation.TabIndex = 0;
            this.panelAnimation.Paint += new System.Windows.Forms.PaintEventHandler(this.panelAnimation_Paint);
            // 
            // panelTorqueGraph
            // 
            this.panelTorqueGraph.BackColor = System.Drawing.Color.LightGray;
            this.panelTorqueGraph.Location = new System.Drawing.Point(1062, 15);
            this.panelTorqueGraph.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.panelTorqueGraph.Name = "panelTorqueGraph";
            this.panelTorqueGraph.Size = new System.Drawing.Size(603, 567);
            this.panelTorqueGraph.TabIndex = 1;
            this.panelTorqueGraph.Paint += new System.Windows.Forms.PaintEventHandler(this.panelTorqueGraph_Paint);
            // 
            // numericUpDownJointCount
            // 
            this.numericUpDownJointCount.Location = new System.Drawing.Point(1205, 619);
            this.numericUpDownJointCount.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.numericUpDownJointCount.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.numericUpDownJointCount.Name = "numericUpDownJointCount";
            this.numericUpDownJointCount.Size = new System.Drawing.Size(160, 22);
            this.numericUpDownJointCount.TabIndex = 2;
            this.numericUpDownJointCount.Value = new decimal(new int[] {
            2,
            0,
            0,
            0});
            this.numericUpDownJointCount.ValueChanged += new System.EventHandler(this.numericUpDownJointCount_ValueChanged);
            // 
            // labelJointCount
            // 
            this.labelJointCount.AutoSize = true;
            this.labelJointCount.Location = new System.Drawing.Point(1059, 622);
            this.labelJointCount.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelJointCount.Name = "labelJointCount";
            this.labelJointCount.Size = new System.Drawing.Size(110, 16);
            this.labelJointCount.TabIndex = 3;
            this.labelJointCount.Text = "Number of Joints:";
            // 
            // flowLayoutThetaInputs
            // 
            this.flowLayoutThetaInputs.Location = new System.Drawing.Point(1062, 669);
            this.flowLayoutThetaInputs.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.flowLayoutThetaInputs.Name = "flowLayoutThetaInputs";
            this.flowLayoutThetaInputs.Size = new System.Drawing.Size(533, 123);
            this.flowLayoutThetaInputs.TabIndex = 4;
            // 
            // buttonPlay
            // 
            this.buttonPlay.Location = new System.Drawing.Point(1062, 590);
            this.buttonPlay.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonPlay.Name = "buttonPlay";
            this.buttonPlay.Size = new System.Drawing.Size(100, 28);
            this.buttonPlay.TabIndex = 5;
            this.buttonPlay.Text = "Play";
            this.buttonPlay.UseVisualStyleBackColor = true;
            this.buttonPlay.Click += new System.EventHandler(this.buttonPlay_Click);
            // 
            // buttonPause
            // 
            this.buttonPause.Location = new System.Drawing.Point(1182, 590);
            this.buttonPause.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonPause.Name = "buttonPause";
            this.buttonPause.Size = new System.Drawing.Size(100, 28);
            this.buttonPause.TabIndex = 6;
            this.buttonPause.Text = "Pause";
            this.buttonPause.UseVisualStyleBackColor = true;
            this.buttonPause.Click += new System.EventHandler(this.buttonPause_Click);
            // 
            // buttonStop
            // 
            this.buttonStop.Location = new System.Drawing.Point(1302, 590);
            this.buttonStop.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonStop.Name = "buttonStop";
            this.buttonStop.Size = new System.Drawing.Size(100, 28);
            this.buttonStop.TabIndex = 7;
            this.buttonStop.Text = "Stop";
            this.buttonStop.UseVisualStyleBackColor = true;
            this.buttonStop.Click += new System.EventHandler(this.buttonStop_Click);
            // 
            // labelTorqueTheta
            // 
            this.labelTorqueTheta.AutoSize = true;
            this.labelTorqueTheta.Location = new System.Drawing.Point(1059, 649);
            this.labelTorqueTheta.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelTorqueTheta.Name = "labelTorqueTheta";
            this.labelTorqueTheta.Size = new System.Drawing.Size(134, 16);
            this.labelTorqueTheta.TabIndex = 8;
            this.labelTorqueTheta.Text = "Torque / Theta (deg):";
            // 
            // numericUpDownPayload
            // 
            this.numericUpDownPayload.Location = new System.Drawing.Point(1525, 619);
            this.numericUpDownPayload.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.numericUpDownPayload.Name = "numericUpDownPayload";
            this.numericUpDownPayload.Size = new System.Drawing.Size(53, 22);
            this.numericUpDownPayload.TabIndex = 9;
            this.numericUpDownPayload.ValueChanged += new System.EventHandler(this.numericUpDownPayload_ValueChanged);
            // 
            // labelPayload
            // 
            this.labelPayload.AutoSize = true;
            this.labelPayload.Location = new System.Drawing.Point(1405, 622);
            this.labelPayload.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelPayload.Name = "labelPayload";
            this.labelPayload.Size = new System.Drawing.Size(99, 16);
            this.labelPayload.TabIndex = 10;
            this.labelPayload.Text = "Payload (units):";
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1678, 1055);
            this.Controls.Add(this.labelPayload);
            this.Controls.Add(this.numericUpDownPayload);
            this.Controls.Add(this.labelTorqueTheta);
            this.Controls.Add(this.buttonStop);
            this.Controls.Add(this.buttonPause);
            this.Controls.Add(this.buttonPlay);
            this.Controls.Add(this.flowLayoutThetaInputs);
            this.Controls.Add(this.labelJointCount);
            this.Controls.Add(this.numericUpDownJointCount);
            this.Controls.Add(this.panelTorqueGraph);
            this.Controls.Add(this.panelAnimation);
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "Form1";
            this.Text = "Joint Torque Visualizer";
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownJointCount)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownPayload)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panelAnimation;
        private System.Windows.Forms.Panel panelTorqueGraph;
        private System.Windows.Forms.NumericUpDown numericUpDownJointCount;
        private System.Windows.Forms.Label labelJointCount;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutThetaInputs;
        private System.Windows.Forms.Button buttonPlay;
        private System.Windows.Forms.Button buttonPause;
        private System.Windows.Forms.Button buttonStop;
        private System.Windows.Forms.Label labelTorqueTheta;
        private System.Windows.Forms.NumericUpDown numericUpDownPayload;
        private System.Windows.Forms.Label labelPayload;
    }
}
